version: '3.8'
services:
  mysql-db:
#    build: ./mysql-database
    image: clientchien123/mysql-onlinetutors:latest
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
#      MYSQL_DATABASE: onlinetutors
    ports:
      - "3308:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-p123456"]
      interval: 10s
      timeout: 5s
      retries: 5
#    volumes:
#      # Mount để lưu DB trên máy host
#      - mysql_data:/var/lib/mysql
#
#      # Import DB khi container chạy lần đầu
#      - ./onlinetutors.sql:/docker-entrypoint-initdb.d/onlinetutors.sql


  onlinetutors:
    image: clientchien123/onlinetutors:latest
#    build: .
    container_name: onlinetutors
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      mysql-db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/onlinetutors_test
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123456
      SPRING_SENDGRID_API_KEY: ${SENDGRID_API_KEY}
    #      SENDGRID_API_KEY: your_sendgrid_api_key_here
    volumes:
      - ./uploads:/app/uploads
#volumes:
#  mysql_data: